### ISSUE TITLE
api

### ISSUE THREAD

**Issue by sgamesdev** [liebki/RawgNET#1]
How do i get the game achievements

**Comment by liebki** [comment]
Hi,

there is a "ParentAchievementsCount" and a "AchievementsCount" field, in the Game.cs

No real way to get the achievements as list or object etc.

I'm checking on this in a few days, to see if I can integrate it in any way.

Greetings

**Comment by sgamesdev** [comment]
Apparently the data location is different https://api.rawg.io/api/games/{id}/achievements?

**Comment by liebki** [comment]
Just to let you know, I think I can upload it tomorrow.
