### ISSUE TITLE
Achievement Image field returns null 

### ISSUE THREAD

**Issue by sgamesdev** [liebki/RawgNET#10]
When quering besiege RawgNET.Achievement.Image.get returned null.

**Comment by liebki** [comment]
Always tell me what ur querying, like the input, I need details

**Comment by sgamesdev** [comment]
this is the input "besiege "

**Comment by liebki** [comment]
Gonna look into it

**Comment by sgamesdev** [comment]
i can't figure out the problem

**Comment by liebki** [comment]
No worries, I'm sure it's an easy fix I'm just occupied, that's why I can't work on it right now.

**Comment by liebki** [comment]
So, I couldn't find any problems when querying besiege.

1. You wrote "besiege " not "besiege", that's a critical point
2. I checked a few screenshots and achievements online, seems to work okay

I used the code, that is used in the demo so I didn't change anything.


[rawgnet-issue10.txt](https://github.com/liebki/RawgNET/files/9442277/rawgnet-issue10.txt)

**Comment by sgamesdev** [comment]
I don't know why in my code this error happens with this code 
  foreach (Achievement item in game.Achievements)
           {
                achivementpresenter.Children.Add(new AchievementItemControl(item.Image.ToString(), item.Name, item.Description, item.Percent));
                
           }

but for this one  MessageBox.Show(item.Image.ToString()); works perfectly

**Comment by sgamesdev** [comment]
i fixed it , i put it in a try medthod
