### ISSUE TITLE
List

### ISSUE THREAD

**Issue by sgamesdev** [liebki/RawgNET#3]
How do i make a foreach(game Achievement ) {}

**Comment by liebki** [comment]
I have to say it's not that obvious, I will fix the naming to make it more clear..

**Example**:
```
Game game = client.GetGameData("gtav", true);
foreach (Result item in game.Achievements)
{
    Console.WriteLine($"------ {Environment.NewLine} Name: {item.Name} {Environment.NewLine} Description: {item.Description} {Environment.NewLine} Image: {item.Image} {Environment.NewLine}");
}
```
**Example output:**
<img width="598" alt="image" src="https://user-images.githubusercontent.com/71221724/184960922-bc78be19-03f0-4d13-9c50-d1d097b3d91b.png">


But be aware, the achievements are only available, when GetGameData has _true_ as second parameter.

Greetings from germany :)

**Comment by liebki** [comment]
Closed by accident.

**Comment by sgamesdev** [comment]
I figured that out , there is  a problem with the achievement list , it always returns null

**Comment by sgamesdev** [comment]
You did a great job with this , Thank You
