### ISSUE TITLE
Error when querying games

### ISSUE THREAD

**Issue by sgamesdev** [liebki/RawgNET#5]
On some games this happen
![fix](https://user-images.githubusercontent.com/72159024/184971960-f1b1f52d-4391-4575-b251-ffb17ddaa36e.PNG)
s

**Comment by liebki** [comment]
I'm looking into it tomorrow, I don't know what that is right now

**Comment by liebki** [comment]
@sgamesdev what Games are you querying? There is at least one game, which's data is missing and (at least) one field is null, that's why the error is thrown.

Do you have discord etc.?

**Comment by sgamesdev** [comment]
Yes edcelmare#9370

**Comment by sgamesdev** [comment]
try quering five nights at freddy's (five-nights-at-freddys)

**Comment by liebki** [comment]
Okay, should be fixed
